//删除主表信息,同时删除从表信息
CREATE OR REPLACE TRIGGER TR_DB_TA
BEFORE DELETE
ON TA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
delete TB where item=:OLD.item;
   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END TR_DB_TA;